-- Traducciones de ejercicios - Parte 1
-- Ejecutar en Supabase SQL Editor

UPDATE exercise_videos SET name_en = 'Ab Wheel Rollout' WHERE canonical_name = 'Abdominales  Con Rueda';
UPDATE exercise_videos SET name_en = 'Alternating Leg Crunches' WHERE canonical_name = 'Abdominales Crunch Alternando Piernas';
UPDATE exercise_videos SET name_en = 'Bench Leg Tucks' WHERE canonical_name = 'Abdominales En Banco Encogimiento De Piernas';
UPDATE exercise_videos SET name_en = '45 Degree Oblique Crunches' WHERE canonical_name = 'Abdominales Oblicuos En Maq 45';
UPDATE exercise_videos SET name_en = 'Plank with Alternating Leg Raise' WHERE canonical_name = 'Abdominales Plancha C/Elevacion De Pierna Alt';
UPDATE exercise_videos SET name_en = 'Machine Hip Abduction' WHERE canonical_name = 'Abductor En Maquina';
UPDATE exercise_videos SET name_en = 'Adductor Stretch' WHERE canonical_name = 'Adductor Stretch';
UPDATE exercise_videos SET name_en = 'Machine Hip Adduction' WHERE canonical_name = 'Aductor En Maq';
UPDATE exercise_videos SET name_en = 'Seated Machine Hip Adduction' WHERE canonical_name = 'Aductor En Maq Sentad';
UPDATE exercise_videos SET name_en = 'Neutral Grip Dumbbell Wrist Curl' WHERE canonical_name = 'Antebrazo Agarra Neutro C/Manc';
UPDATE exercise_videos SET name_en = 'Kettlebell Wrist Curl' WHERE canonical_name = 'Antebrazo C/Kettlebell';
UPDATE exercise_videos SET name_en = 'Forearm Exercises' WHERE canonical_name = 'Antebrazos';
UPDATE exercise_videos SET name_en = 'Pronated Barbell Wrist Curls' WHERE canonical_name = 'Antebrazos A/Prono Con Barra';
UPDATE exercise_videos SET name_en = 'Dumbbell Flyes' WHERE canonical_name = 'Aperturas Con Mancuernas';
UPDATE exercise_videos SET name_en = 'Machine Flyes' WHERE canonical_name = 'Aperturas En Máquina';
UPDATE exercise_videos SET name_en = 'Battle Ropes' WHERE canonical_name = 'Battle Ropes';
UPDATE exercise_videos SET name_en = 'Single Arm Preacher Curl' WHERE canonical_name = 'Biceps A Un Brazo En Banco Scoot';
UPDATE exercise_videos SET name_en = 'Single Arm High Cable Curl' WHERE canonical_name = 'Biceps A Un Brazo P/Alta';
UPDATE exercise_videos SET name_en = 'Straight Bar Cable Curls' WHERE canonical_name = 'Biceps Barra Recta En Polea Baja';
UPDATE exercise_videos SET name_en = 'Close Grip Resistance Band Curls' WHERE canonical_name = 'Biceps Con Banda Elastica Agarre Cerrado';
UPDATE exercise_videos SET name_en = 'Close Grip Barbell Curls' WHERE canonical_name = 'Biceps Con Barra Agarre Cerrado';
UPDATE exercise_videos SET name_en = 'Wide Grip EZ Bar Curls' WHERE canonical_name = 'Biceps Con Barra W A/Amplio';
UPDATE exercise_videos SET name_en = 'Close Grip EZ Bar Curls' WHERE canonical_name = 'Biceps Con Barra W Agarre Cerrado';
UPDATE exercise_videos SET name_en = 'Standing Neutral Grip Barbell Curls' WHERE canonical_name = 'Biceps De Parado Con Barra Agarre Neutro';
UPDATE exercise_videos SET name_en = 'Standing Shoulder Width EZ Bar Curls' WHERE canonical_name = 'Biceps De Parado Con Barra W A/Ancho De Hombros';
UPDATE exercise_videos SET name_en = 'Incline Dumbbell Curls' WHERE canonical_name = 'Biceps En Banco Inclinado Simultaneo';
UPDATE exercise_videos SET name_en = 'Machine Bicep Curls' WHERE canonical_name = 'Biceps En Maquina';
UPDATE exercise_videos SET name_en = 'Single Arm Preacher Hammer Curl' WHERE canonical_name = 'Biceps Martillo A Un Brazo En B/Scoot';
UPDATE exercise_videos SET name_en = 'Alternating Resistance Band Hammer Curls' WHERE canonical_name = 'Biceps Martillo Alternado Con Banda Eslatica';
UPDATE exercise_videos SET name_en = 'Seated Alternating Hammer Curls' WHERE canonical_name = 'Biceps Martillo Alternado Sentado';
UPDATE exercise_videos SET name_en = 'Incline Simultaneous Hammer Curls' WHERE canonical_name = 'Biceps Martillo Banco Inclinado Simultaneo';
UPDATE exercise_videos SET name_en = 'Standing Wide Grip Barbell Curls' WHERE canonical_name = 'Biceps Par5ado Con Barra Agarre Amplio';
UPDATE exercise_videos SET name_en = 'Stationary Bike' WHERE canonical_name = 'Bicicleta Estática';
UPDATE exercise_videos SET name_en = 'Standing Alternating Hammer Curls' WHERE canonical_name = 'Bicpes Martillo De Parado Alternado';
UPDATE exercise_videos SET name_en = 'Boat Stretch' WHERE canonical_name = 'Boat Stretch';
UPDATE exercise_videos SET name_en = 'Box Jumps' WHERE canonical_name = 'Box Jumps';
UPDATE exercise_videos SET name_en = 'Barbell Good Mornings' WHERE canonical_name = 'Buen Dia C/Barra';
UPDATE exercise_videos SET name_en = 'Smith Machine Bulgarian Split Squats' WHERE canonical_name = 'Bulgaras En Smith';
UPDATE exercise_videos SET name_en = 'Burpees' WHERE canonical_name = 'Burpees';
UPDATE exercise_videos SET name_en = 'Light Walk' WHERE canonical_name = 'Caminata Ligera';
UPDATE exercise_videos SET name_en = 'Stationary Bike' WHERE canonical_name = 'Cardio: Bicicleta Estática';
UPDATE exercise_videos SET name_en = 'Treadmill Running' WHERE canonical_name = 'Cardio: Correr En Cinta';
UPDATE exercise_videos SET name_en = 'Elliptical' WHERE canonical_name = 'Cardio: Elíptica';
UPDATE exercise_videos SET name_en = 'Stair Climber' WHERE canonical_name = 'Cardio: Escaladora';
UPDATE exercise_videos SET name_en = 'Rowing Machine' WHERE canonical_name = 'Cardio: Máquina De Remo';
UPDATE exercise_videos SET name_en = 'Jump Rope' WHERE canonical_name = 'Cardio: Saltar La Cuerda';
UPDATE exercise_videos SET name_en = 'Interval Running' WHERE canonical_name = 'Carrera En Intervalos';
UPDATE exercise_videos SET name_en = 'Indoor Cycling Intervals' WHERE canonical_name = 'Ciclismo Indoor En Intervalos';
UPDATE exercise_videos SET name_en = 'Decline Dumbbell Flyes with Twist' WHERE canonical_name = 'Cierre Declinado Con Manc Twist';
UPDATE exercise_videos SET name_en = 'Flat Bench Cable Flyes' WHERE canonical_name = 'Cierre Pectoral En Banco Plano/Polea';
UPDATE exercise_videos SET name_en = 'High Cable Flyes' WHERE canonical_name = 'Cierre Pectoral En Polea Alta';
UPDATE exercise_videos SET name_en = 'Low Cable Flyes' WHERE canonical_name = 'Cierre Pectoral P/Baja';
UPDATE exercise_videos SET name_en = 'Clamshells' WHERE canonical_name = 'Clamshells';
UPDATE exercise_videos SET name_en = 'Kettlebell Clean' WHERE canonical_name = 'Clean Con Kettlebell';
UPDATE exercise_videos SET name_en = 'Low Cable Crossover' WHERE canonical_name = 'Cruce De Poleas Bajo';
UPDATE exercise_videos SET name_en = 'High Cable Crossover' WHERE canonical_name = 'Cruces En Polea Alta';
UPDATE exercise_videos SET name_en = 'Machine Crunches' WHERE canonical_name = 'Crunch En Máquina';
UPDATE exercise_videos SET name_en = 'Floor Crunches' WHERE canonical_name = 'Crunch En Suelo';
UPDATE exercise_videos SET name_en = 'Crunches' WHERE canonical_name = 'Crunches';
UPDATE exercise_videos SET name_en = 'Bicep Curls' WHERE canonical_name = 'Curl';
UPDATE exercise_videos SET name_en = 'Alternating Bicep Curls' WHERE canonical_name = 'Curl Bíceps Alterno';
UPDATE exercise_videos SET name_en = 'Concentration Curls' WHERE canonical_name = 'Curl Concentrado';
UPDATE exercise_videos SET name_en = 'Straight Barbell Bicep Curls' WHERE canonical_name = 'Curl De Bíceps Con Barra Recta';
UPDATE exercise_videos SET name_en = 'EZ Bar Bicep Curls' WHERE canonical_name = 'Curl De Bíceps Con Barra Z';
UPDATE exercise_videos SET name_en = 'Incline Bench Curls' WHERE canonical_name = 'Curl En Banco Inclinado';
UPDATE exercise_videos SET name_en = 'Leg Curls' WHERE canonical_name = 'Curl Femoral';
UPDATE exercise_videos SET name_en = 'Seated Leg Curls' WHERE canonical_name = 'Curl Femoral Sentado';
UPDATE exercise_videos SET name_en = 'Lying Leg Curls' WHERE canonical_name = 'Curl Femoral Tumbado';
UPDATE exercise_videos SET name_en = 'Machine Leg Curls' WHERE canonical_name = 'Curl Femorales En Maquina';
UPDATE exercise_videos SET name_en = 'Hammer Curls' WHERE canonical_name = 'Curl Martillo';
UPDATE exercise_videos SET name_en = 'Dead Bug' WHERE canonical_name = 'Dead Bug';
UPDATE exercise_videos SET name_en = 'Double High Cable Bicep Curls' WHERE canonical_name = 'Doble Biceps En Polea Alta';
UPDATE exercise_videos SET name_en = 'Pull-ups' WHERE canonical_name = 'Dominadas';
UPDATE exercise_videos SET name_en = 'Assisted Pull-ups' WHERE canonical_name = 'Dominadas Asistidas';
UPDATE exercise_videos SET name_en = 'Band-Assisted Pull-ups' WHERE canonical_name = 'Dominadas Con Banda';
UPDATE exercise_videos SET name_en = 'Pronated Pull-ups' WHERE canonical_name = 'Dominadas Pronas';
UPDATE exercise_videos SET name_en = 'Chin-ups' WHERE canonical_name = 'Dominadas Supinas';
UPDATE exercise_videos SET name_en = 'Dragon Flag' WHERE canonical_name = 'Dragon Flag';
UPDATE exercise_videos SET name_en = 'Standing Calf Raises' WHERE canonical_name = 'Elevación De Gemelos De Pie';
UPDATE exercise_videos SET name_en = 'Seated Calf Raises' WHERE canonical_name = 'Elevación De Gemelos Sentado';
UPDATE exercise_videos SET name_en = 'Hip Raise with Abduction' WHERE canonical_name = 'Elevacion De Pelvis Con Abducion';
UPDATE exercise_videos SET name_en = 'Machine Calf Raises' WHERE canonical_name = 'Elevaciones De Talones Máquina';
UPDATE exercise_videos SET name_en = 'Front Raises' WHERE canonical_name = 'Elevaciones Frontales';
UPDATE exercise_videos SET name_en = 'Dumbbell Lateral Raises' WHERE canonical_name = 'Elevaciones Laterales Con Mancuernas';
UPDATE exercise_videos SET name_en = 'Barbell Shrugs' WHERE canonical_name = 'Encogimientos Barra';
UPDATE exercise_videos SET name_en = 'Dumbbell Shrugs' WHERE canonical_name = 'Encogimientos De Trapecio Con Mancuernas';
UPDATE exercise_videos SET name_en = 'Ab Stretch' WHERE canonical_name = 'Estiramiento Abdominal';
UPDATE exercise_videos SET name_en = 'Bulgarian Squat Stretch' WHERE canonical_name = 'Estiramiento Bulgaro Squat';
UPDATE exercise_videos SET name_en = 'Butterfly Stretch' WHERE canonical_name = 'Estiramiento Butterflay';
UPDATE exercise_videos SET name_en = 'Quad Stretch' WHERE canonical_name = 'Estiramiento De Cuádriceps';
UPDATE exercise_videos SET name_en = 'Lower Back Stretch' WHERE canonical_name = 'Estiramiento De Espalda Baja';
UPDATE exercise_videos SET name_en = 'Chest Stretch' WHERE canonical_name = 'Estiramiento De Pecho';
UPDATE exercise_videos SET name_en = 'Back Stretch' WHERE canonical_name = 'Estiramiento Espalda';
UPDATE exercise_videos SET name_en = 'Back and Shoulder Stretch' WHERE canonical_name = 'Estiramiento Espalda , Hombros';
UPDATE exercise_videos SET name_en = 'Hamstring Stretch' WHERE canonical_name = 'Estiramiento Femorales';
UPDATE exercise_videos SET name_en = 'Calf Stretch' WHERE canonical_name = 'Estiramiento Gemelos';
UPDATE exercise_videos SET name_en = 'Shoulder Stretch' WHERE canonical_name = 'Estiramiento Hombros';
UPDATE exercise_videos SET name_en = 'Hands Behind Back Stretch' WHERE canonical_name = 'Estiramiento Manos Al Rededor De La Espalda';
UPDATE exercise_videos SET name_en = 'Pectoral Stretch' WHERE canonical_name = 'Estiramiento Pectoral';
UPDATE exercise_videos SET name_en = 'Chest and Shoulder Stretch' WHERE canonical_name = 'Estiramiento Pectoral , Hombros';

-- Verificar resultados
SELECT canonical_name, name_en FROM exercise_videos WHERE name_en IS NOT NULL ORDER BY canonical_name LIMIT 100;
